version: "3.7"
services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - db
  testing:
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - ./:/app
    env_file: ./.env.testing

  nginx:
    build:
      context: .
      dockerfile: www.Dockerfile
    ports:
      - 80:80
    volumes:
      - ./:/app
    depends_on:
      - backend
  db:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: test_auto_production
    command: --default-authentication-plugin=mysql_native_password
  db_test:
    image: mysql:8
    ports:
      - 3307:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: test_auto_testing
    command: --default-authentication-plugin=mysql_native_password

