<?php

namespace Http\Controllers;

use App\Http\Controllers\CarController;
use App\Models\Car;
use Laravel\Lumen\Testing\DatabaseMigrations;
use TestCase;

class CarControllerTest extends TestCase
{
    use DatabaseMigrations;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Car::factory()->create();
    }

    public function testGet()
    {
        $response = $this->get('/api/cars');
        $response->seeJsonStructure(["data" => [['id', 'name', 'created_at', 'updated_at']]]);
    }
}
